image: Visual Studio 2017
configuration: Release

install:
    - cmake . -G "Visual Studio 15 2017 Win64"

build:
  project: embree.sln

artifacts:
    - path: bin\Release\*.*
      name: $(APPVEYOR_PROJECT_NAME)
